# Agent Parameters
AGGRESSIVE_BOUNDS = (0, 1)
HARVEST_BOUNDS = (0, 1)
MEMORY_BOUNDS = (0, 20)
INTERACTION_RADIUS = 1
VISION_RADIUS = 6
DISTANCE_PER_STEP = 0.5
CHANCE_TO_REMEMBER_BUSH = 0.3
CHANCE_TO_REMEMBER_CAVE = 0.7
CHANCE_TO_USE_MEMORY = 1
CHANCE_TO_GET_BORED = 0.05
FAT_PRESERVATION_PERCENT = 0.5
# Calorie parameters
MAX_AGGR_CAL = 200
MAX_HARVEST_CAL = 100
CAL_PER_MEM = 10
# Calories that various activities cost
WALK_CAL_COST = 0.5
HARVEST_CAL_COST = 4
FIGHT_CAL_COST = 10
# Initialization
INIT_NUM_AGENTS = 100  # Number of agents could change
INIT_NUM_CAVES = 30
INIT_CAVE_CAP = (7, 12)
INIT_NUM_BUSHES = 50
INIT_BUSH_CAP = (1000, 1500)
MAP_SIZE = 50  # Square
# How long to run
NUM_DAYS = 100
STEPS_PER_DAY = 250
# How much of the day to consider morning and evening.
MORNING_PERCENT = 0.15
EVENING_PERCENT = 0.15
# Checkpointing
DAYS_PER_CHECKPOINT = 1
# Visualization
VISUALIZE = False
AS_MP4 = False
NUM_BINS = 25
